name: my_test

on: push
jobs:
  start_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          pip install pytest
          pip3 install requests
          poetry install
          pip install flake8
          poetry add pytest
          pip install pytest-cov
      - name: Run linter
        run: |
          poetry build
          make install
          make lint
          make testing
          pytest
      - name: climate coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
         CC_TEST_REPORTER_ID: 1d4dd2831966ea3c0f68072bf0dc749a239006068f35422c35ca12d70173d648
        with:
         coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
         debug: true
