name: my_test

on: push
jobs:
  start_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          pip install flake8
      - name: Run linter
        run: |
          make lint